name: bluemoon

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: bluemoon_sql_server
    ports:
      - "1435:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=etronTR04
    networks:
      - backend-net

  sql-init:
    image: mcr.microsoft.com/mssql-tools
    container_name: bluemoon_sql_init
    depends_on:
      - sqlserver
    entrypoint: >
      bash -c "
      sleep 20 &&
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P 'etronTR04' -i /init/init.sql
      "
    volumes:
      - ./init:/init
    networks:
      - backend-net

  redis:
    image: "redis:7-alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: .
    container_name: bluemoon_backend
    depends_on:
      - sqlserver
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=BlueMoon;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=etronTR04
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    ports:
      - "8000:8000"
    networks:
      - backend-net

networks:
  backend-net:
